apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  db_host: book-rds.cebwcey862sw.us-east-1.rds.amazonaws.com
  db_username: admin
  db_password: yaswanth
 

# https://www.base64decode.org/
